// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtf3nFkcZKrJVZngCgFGblFRQJbDTNdQY',
    appId: '1:763054872497:web:d378abc427f7d2e68c0f90',
    messagingSenderId: '763054872497',
    projectId: 'carelink-app-v2',
    authDomain: 'carelink-app-v2.firebaseapp.com',
    storageBucket: 'carelink-app-v2.firebasestorage.app',
    measurementId: 'G-JK0V4Q0HVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC22JO2wAfy4I62KQfvZxF61-chfJUETdM',
    appId: '1:763054872497:android:da786ae0f83a5c528c0f90',
    messagingSenderId: '763054872497',
    projectId: 'carelink-app-v2',
    storageBucket: 'carelink-app-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0o239x68o8w9wkzHrPhhW--M312BWI0I',
    appId: '1:763054872497:ios:89e278e61e60d4738c0f90',
    messagingSenderId: '763054872497',
    projectId: 'carelink-app-v2',
    storageBucket: 'carelink-app-v2.firebasestorage.app',
    iosBundleId: 'com.example.carelinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0o239x68o8w9wkzHrPhhW--M312BWI0I',
    appId: '1:763054872497:ios:89e278e61e60d4738c0f90',
    messagingSenderId: '763054872497',
    projectId: 'carelink-app-v2',
    storageBucket: 'carelink-app-v2.firebasestorage.app',
    iosBundleId: 'com.example.carelinkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtf3nFkcZKrJVZngCgFGblFRQJbDTNdQY',
    appId: '1:763054872497:web:8e12bbec8b3cfe6f8c0f90',
    messagingSenderId: '763054872497',
    projectId: 'carelink-app-v2',
    authDomain: 'carelink-app-v2.firebaseapp.com',
    storageBucket: 'carelink-app-v2.firebasestorage.app',
    measurementId: 'G-MCEQ7RKCS3',
  );

}