// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCqnPBPoaDgzr6-r8fmjf4zRyqvJLFwMY',
    appId: '1:287651637943:web:3de304736efca920dbbb32',
    messagingSenderId: '287651637943',
    projectId: 'carelink-b0c59',
    authDomain: 'carelink-b0c59.firebaseapp.com',
    databaseURL: 'https://carelink-b0c59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carelink-b0c59.firebasestorage.app',
    measurementId: 'G-R83W0V1GVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdCEL7DQWzBIfZqDDlcUeJbCyZElTFWN8',
    appId: '1:287651637943:android:50851ea608b5e2d0dbbb32',
    messagingSenderId: '287651637943',
    projectId: 'carelink-b0c59',
    databaseURL: 'https://carelink-b0c59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carelink-b0c59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_pOSA_QG-TyGavP8yP3H373M4PGkq4yA',
    appId: '1:287651637943:ios:acddba7b8d206763dbbb32',
    messagingSenderId: '287651637943',
    projectId: 'carelink-b0c59',
    databaseURL: 'https://carelink-b0c59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carelink-b0c59.firebasestorage.app',
    iosBundleId: 'com.example.carelinkApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_pOSA_QG-TyGavP8yP3H373M4PGkq4yA',
    appId: '1:287651637943:ios:acddba7b8d206763dbbb32',
    messagingSenderId: '287651637943',
    projectId: 'carelink-b0c59',
    databaseURL: 'https://carelink-b0c59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carelink-b0c59.firebasestorage.app',
    iosBundleId: 'com.example.carelinkApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCqnPBPoaDgzr6-r8fmjf4zRyqvJLFwMY',
    appId: '1:287651637943:web:d9fd12d650a687a3dbbb32',
    messagingSenderId: '287651637943',
    projectId: 'carelink-b0c59',
    authDomain: 'carelink-b0c59.firebaseapp.com',
    databaseURL: 'https://carelink-b0c59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carelink-b0c59.firebasestorage.app',
    measurementId: 'G-YD3LPC8D3Z',
  );
}
